extends: '@zakodium/eslint-config/typescript-react'
rules:
  '@typescript-eslint/prefer-regexp-exec': off
  # TODO: re-enable this rule once eslint-plugin-import supports the "exports" field.
  # See https://github.com/benmosher/eslint-plugin-import/issues/2132
  'import/no-unresolved': off
  'jest/no-done-callback': off
